### ISSUE TITLE
composer.json broke by hook setup

### ISSUE THREAD

**Issue by sinkcup** [larapack/hooks#41]
- Hooks Version: v1.0.8
- Laravel Version: 5.7.19
- PHP Version: 7.2.10

### Description:
`composer.json` broke by hook setup

### Steps To Reproduce:

```
php artisan hook:setup
git diff composer.json
```

Error: No newline at end of file

![image](https://user-images.githubusercontent.com/4971414/51427395-924d6900-1c32-11e9-8146-4da300d2a5eb.png)

**Comment by fletch3555** [comment]
Same as the Voyager issue you created... uhhh what?

There's no error in your screenshot

**Comment by sinkcup** [comment]
Error: No newline at end of file

do you known Linux/Mac demand "every line in text should end with a line break"?

**Comment by fletch3555** [comment]
Does it cause you any problems? Thats not a "demand" as much as it is a "standard". If it's not causing problems (which I know its not since 1000's of devs have been using this for over a year), then just ignore it. Or add it back yourself

**Comment by sinkcup** [comment]
follow standards, break rules.

It make big problem: `composer.json` be changed for nothing, add rubbish history to git, git warning, code can't commit.

**Comment by fletch3555** [comment]
It doesn't add anything to git, that's on you as the dev.  You're welcome to add the line before committing if you so desire.  There's no got warning at all, not will it block you from committing other changes.

I'm not saying you (we) shouldn't follow standards. What I am saying is that you're making a huge deal out of nothing

**Comment by sinkcup** [comment]
There is testing before commit, you known?

Every time I run `php artisan voyager:install && phpunit`, then `composer.json` changed, you say it's nothing?

**Comment by fletch3555** [comment]
We have no control over any pre-commit hooks you may have added to your project.  There is nothing in the core functionality of git that would block the commit simply for a missing newline at the end of a file.  Git simply doesn't care.

**Comment by sinkcup** [comment]
this install changes `composer.json`, whatever the content, git care changes.

your bug trouble all developers, every time "change back manually" is not a good idea.

**Comment by sinkcup** [comment]
@emptynick is anybody there?

**Comment by emptynick** [comment]
> your bug trouble all developers

You are the first one with troubles because of this

**Comment by sinkcup** [comment]
ha ha. in any case, a package should not change my `composer.json`

**Comment by emptynick** [comment]
If you dont want hooks to change your `composer.json` (what it does when installing/uninstalling hooks), remove it.

**Comment by sinkcup** [comment]
I had fix it, check the PR https://github.com/larapack/hooks/pull/42

**Comment by sinkcup** [comment]
bug is bug, small bug is bug too. Don't look for any excuses.
