### ISSUE TITLE
Certificate is expired

### ISSUE THREAD

**Issue by fenixrts** [larapack/hooks#52]
- Hooks Version: #.#.#
- Laravel Version: #.#.#
- PHP Version:

### Description:
Hi. Yours certificate is expired. Composer cannot install project dependencies. Please, fix it.

### Steps To Reproduce:
compsoer install

**Comment by ollyollyollygarbott** [comment]
+1 here

**Comment by fibergateproj** [comment]
+1

**Comment by WendyHoogendoorn-SWIS** [comment]
+1

**Comment by ewanyonyi** [comment]
Kindly work on this, composer is completely not working now. You can use cron jobs to automatically update the certificate.

**Comment by siddiquin** [comment]
Meanwhile, you can change your composer file like this, and this will pull the package.json from larapack.io

![CapturFiles-Aug-20-2021_22 09 01](https://user-images.githubusercontent.com/6883419/130307283-2805240b-f71c-4ee1-9721-ffa55b67d572.jpg)

**Comment by Alwyn-RM** [comment]
Fix no longer working. Site is down. Fix this asap please, we can't deploy at the moment.

**Comment by fletch3555** [comment]
Cert is valid as of Oct 15 2023
